### ISSUE TITLE
nezobrazuje sa stav hry pre hracov

### ISSUE THREAD

**Issue by japdlsd** [Ninush2498/project#12]
chyba vypis akutalnej stavky, poctu hracov, stavu ich ruk (t.j. kolko maju dokopy kociek, kolko je odkytych na stole), ci dany hrac prehral alebo nie.

Na uvod asi staci posielat len JSON so zamaskovanymi hodnotami, vizual nie je dolezity. Treba vsak uz v tomto stadiu vediet evaluovat, ktora cast herneho stavu ma byt pristupna pre konkretneho hraca.

**Comment by Ninush2498** [comment]
Hotovo ešte na konci zimného semestra, zatiaľ škaredé, ale je to tam.

**Comment by Ninush2498** [comment]
Už hotové úplne.
